controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
   path: /
   controller: App\Controller\HomeController::index

conditions:
   path: /cgu
   controller: App\Controller\HomeController::conditions

confidentialities:
    path: /confidentialities
    controller: App\Controller\HomeController::confidentialities

# ADMINISTRATOR
app_app_user_index:
    path: /admin/users
    controller: App\Controller\UserController::index
    methods:  [GET]

app_user_new:
    path: /admin/users/new
    controller: App\Controller\UserController::new
    methods:  [GET, POST]

app_user_edit:
    path: /admin/users/{id}/edit
    controller: App\Controller\UserController::edit
    methods:  [GET, POST]

app_user_delete:
    path: /admin/users/{id}
    controller: App\Controller\UserController::delete
    methods:  [GET, POST]

app_register:
    path: /admin/register
    controller: App\Controller\RegistrationController::register
    methods:  [GET, POST]

# PRIVACY POLICY
app_privacy_policy:
    path: /privacy-policy
    controller: App\Controller\PrivacyPolicyController::index
    methods:  [GET]

# NEWS LETTERS
app_news_letters_index:
    path: /admin/newsletters
    controller: App\Controller\NewsLettersController::index
    methods:  [GET]

app_news_letters_new:
    path: /newsletters/new
    controller: App\Controller\NewsLettersController::new
    methods:  [GET, POST]

app_news_letters_delete:
    path: /admin/newsletters/{id}
    controller: App\Controller\NewsLettersController::delete
    methods:  [GET, POST]

# GAMES
app_games_index:
    path: /admin/games/
    controller: App\Controller\GamesController::index
    methods:  [GET]

app_games_new:
    path: /admin/games/new
    controller: App\Controller\GamesController::new
    methods:  [GET, POST]

app_games_edit:
    path: /admin/games/{id}/edit
    controller: App\Controller\GamesController::edit
    methods:  [GET, POST]

app_games_show:
    path: /games/{id}/{name}
    controller: App\Controller\GamesController::show
    methods:  [GET]

app_games_delete:
    path: /admin/games/{id}
    controller: App\Controller\GamesController::delete
    methods:  [GET, POST]

# IMAGES
app_images_index:
    path: /admin/images/
    controller: App\Controller\ImagesController::index
    methods:  [GET]

app_images_new:
    path: /admin/images/new
    controller: App\Controller\ImagesController::new
    methods:  [GET, POST]

app_images_edit:
    path: /admin/images/{id}/edit
    controller: App\Controller\ImagesController::edit
    methods:  [GET, POST]

app_images_delete:
    path: /admin/images/{id}
    controller: App\Controller\ImagesController::delete
    methods: [GET, POST]
# PlatForms
app_plate_forms_index:
    path: /admin/plateform/
    controller: App\Controller\PlateFormsController::index
    methods:  [GET]

app_plate_forms_new:
    path: /admin/plateform/new
    controller: App\Controller\PlateFormsController::new
    methods:  [GET, POST]

app_plate_forms_edit:
    path: /admin/plateform/{id}/edit
    controller: App\Controller\PlateFormsController::edit
    methods:  [GET, POST]

app_plate_forms_delete:
    path: /admin/plateform/{id}
    controller: App\Controller\PlateFormsController::delete
    methods: [GET, POST]

# STUDIO
app_studio_index:
    path: /studio/
    controller: App\Controller\StudioController::index
    methods:  [GET]

app_studio_new:
    path: /admin/studio/new
    controller: App\Controller\StudioController::new
    methods:  [GET, POST]

app_studio_edit:
    path: /admin/studio/{id}/edit
    controller: App\Controller\StudioController::edit
    methods:  [GET, POST]

app_studio_delete:
    path: /admin/studio/{id}
    controller: App\Controller\StudioController::delete
    methods: [GET, POST]
    
# WEBSITE
app_websites_index:
    path: /websites/
    controller: App\Controller\WebsitesController::index
    methods:  [GET]

app_websites_new:
    path: /admin/websites/new
    controller: App\Controller\WebsitesController::new
    methods:  [GET, POST]

app_websites_edit:
    path: /admin/websites/{id}/edit
    controller: App\Controller\WebsitesController::edit
    methods:  [GET, POST]

app_websites_delete:
    path: /admin/websites/{id}
    controller: App\Controller\WebsitesController::delete
    methods: [GET, POST]

#WEBGLDEMO
app_webgldemo_index:
    path: /admin/webgldemo/
    controller: App\Controller\WebGLDemoController::index
    methods:  [GET]

app_webgldemo_new:
    path: /admin/webgldemo/new
    controller: App\Controller\WebGLDemoController::new
    methods:  [GET, POST]

app_webgldemo_show:
    path: /demo/{id}/{name}
    controller: App\Controller\WebGLDemoController::show
    methods:  [GET]

app_webgldemo_delete:
    path: /admin/WebGLDemo/{id}
    controller: App\Controller\WebGLDemoController::delete
    methods: [GET, POST]